### ISSUE TITLE
Holding the request results in the request never being finished.

### ISSUE THREAD

**Issue by LukeButters** [yourarj/spring-security-prevent-brute-force#1]
The intention of https://stackoverflow.com/questions/54434679/adding-an-artificial-delay-in-a-spring-security-authenticationprovider-without-m was to add a server side delay in the request without the user needing to be aware that it is occurring.

So what should happen is if a delay is necessary the request should be held open for the delay and then the login attempt should be made with a response to a user.

What actually happens is the request is delayed however the request is not completed.

**Comment by yourarj** [comment]
Fixed the bug. Now the attempt is made after the desired delay and request completes normally. checked up to 130 seconds of delay. The amount of time to wait is exponentially increased after each failed login attempt.
